-- Schéma de référence (scaffolding) — cf. docs/diagrammes/D2-modele-donnees.md
-- Les tables session_cours, presence, exercice, relecture sont ajoutées par
-- les migrations des issues correspondantes (#1, #2, #5, #7), pas ici :
-- chaque branche d'issue apporte sa propre migration, cf. discipline Git du sujet.

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE formateur (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(255) NOT NULL,
    promotion_id  BIGINT NOT NULL REFERENCES promotion(id)
);
