-- Issue #1 — Le formateur ouvre une session et obtient un code de présence (EF1, RG1)

CREATE TABLE session_cours (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(255) NOT NULL,
    promotion_id   BIGINT NOT NULL REFERENCES promotion(id),
    formateur_id   BIGINT NOT NULL REFERENCES formateur(id),
    code           VARCHAR(16) NOT NULL UNIQUE,
    ouverture_at   TIMESTAMP NOT NULL,
    expiration_at  TIMESTAMP NOT NULL,
    cloture_at     TIMESTAMP NULL,
    statut         VARCHAR(20) NOT NULL
);
