-- Issue #2 — L'étudiant marque sa présence avec un code (EF2-4, RG1-3)

CREATE TABLE presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session_cours(id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant(id),
    source       VARCHAR(20) NOT NULL,
    horodatage   TIMESTAMP NOT NULL,
    CONSTRAINT uq_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);
