-- Issue #5 — L'étudiant dépose le lien de son exercice (EF7-8, RG12)

CREATE TABLE exercice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session_cours(id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant(id),
    lien         VARCHAR(2048) NOT NULL,
    statut       VARCHAR(30) NOT NULL,
    depose_at    TIMESTAMP NOT NULL,
    CONSTRAINT uq_exercice_session_etudiant UNIQUE (session_id, etudiant_id)
);
