-- Issue #7 — Le système assigne un relecteur aléatoire (EF10, RG5-7)

CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL UNIQUE REFERENCES exercice(id),
    relecteur_id  BIGINT NOT NULL REFERENCES etudiant(id),
    note          INTEGER NULL,
    commentaire   VARCHAR(2000) NULL,
    statut        VARCHAR(20) NOT NULL,
    rendue_at     TIMESTAMP NULL,
    CONSTRAINT chk_note_range CHECK (note IS NULL OR (note BETWEEN 0 AND 20))
);
