-- Étape 3, enveloppe — changement de besoin (RG6 révisée) : un exercice
-- peut désormais avoir jusqu'à DEUX relecteurs différents au lieu d'un seul.
-- Migration additive : V6 n'est pas modifiée, ce qui suit s'applique par-dessus.
--
-- Le nom de la contrainte UNIQUE(exercice_id) posée par V6 est généré
-- automatiquement et diffère selon le moteur (non portable à cibler par un
-- simple DROP CONSTRAINT <nom>) : on recrée donc la table avec la bonne
-- contrainte plutôt que de deviner ce nom. Les données existantes (une
-- relecture par exercice au plus, à ce stade) sont copiées à l'identique,
-- la migration survit donc à une base déjà remplie.

ALTER TABLE relecture RENAME TO relecture_v6;

CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL REFERENCES exercice(id),
    relecteur_id  BIGINT NOT NULL REFERENCES etudiant(id),
    note          INTEGER NULL,
    commentaire   VARCHAR(2000) NULL,
    statut        VARCHAR(20) NOT NULL,
    rendue_at     TIMESTAMP NULL,
    CONSTRAINT chk_relecture_note_range CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
    CONSTRAINT uq_relecture_exercice_relecteur UNIQUE (exercice_id, relecteur_id)
);

INSERT INTO relecture (id, exercice_id, relecteur_id, note, commentaire, statut, rendue_at)
SELECT id, exercice_id, relecteur_id, note, commentaire, statut, rendue_at FROM relecture_v6;

DROP TABLE relecture_v6;
