spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/kfokam48_fullstack
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080

kfokam48:
  presence:
    expiration-minutes: 15
    max-tentatives: 5
    blocage-minutes: 2
